git:
  overrideGpg: true

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

customCommands:
  - key: "<c-i>"
    context: global
    command: "git submodule update --init --recursive"
    description: "Initialize and update submodules"
    loadingText: "Initializing submodules"
    output: log
  - key: "<c-u>"
    context: global
    command: "git submodule update --remote --recursive"
    description: "Update submodules from remotes"
    loadingText: "Updating submodules"
    output: log
  - key: "<c-p>"
    context: global
    command: "git submodule foreach --recursive 'git pull --ff-only'"
    description: "Pull all submodules"
    loadingText: "Pulling submodules"
    output: log
