# name = "luna"
# author = "wtfox"

palette = "luna"

[palettes.luna]
black = "#000000"
red = "#e08585"
green = "#6fbe80"
yellow = "#c2916a"
blue = "#75a1c7"
purple = "#c4a8d6"
cyan = "#75a1c7"
white = "#c7c7c7"
bright-black = "#888888"
bright-red = "#e08585"
bright-green = "#6fbe80"
bright-yellow = "#d9a35a"
bright-blue = "#8c9cb8"
bright-purple = "#c4a8d6"
bright-cyan = "#75a1c7"
bright-white = "#ffffff"

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$cmd_duration\
$line_break\
$python\
$character"""

[os]
disabled = false
format = "[$symbol ](#ffffff)"

[os.symbols]
Macos = ""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[ $branch]($style)"
style = "#F05032"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#ffb86c) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[ $duration]($style)"
style = "yellow"

[nodejs]
format = "[  $version]($style)"
style = "#84ba64"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
